apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: pso.example.com/v1alpha1
kind: VpcEndpoint
metadata:
  name: demo
  namespace: demo
spec:
  subdomainName: "splunk"
  serviceName: "com.amazonaws.vpce.us-east-2.vpce-svc-00935f365dbc6ad80"
  securityGroup:
    ingressRules:
      - fromPort: 9997
        toPort: 9997
        protocol: tcp
