apiVersion: avo.openshift.io/v1alpha1
kind: VpcEndpointAcceptance
metadata:
  name: splunk-acceptance
  namespace: openshift-aws-vpce-operator
spec:
  id: "vpce-svc-06225ed6e3620e8e1"
  assumeRoleArn: "arn:aws-us-gov:iam::486461443045:role/SplunkVpceAcceptance"
  region: "us-gov-west-1"
  acceptanceCriteria:
    awsAccountOperatorAccount:
      namespace: aws-account-operator
