---
apiVersion: avo.openshift.io/v1alpha1
kind: VpcEndpoint
metadata:
  name: demo
spec:
  subdomainName: "splunk"
  serviceName: "com.amazonaws.vpce.us-east-1.vpce-svc-00000000000000000"
  securityGroup:
    ingressRules:
      - fromPort: 9997
        toPort: 9997
        protocol: tcp
  externalNameService:
    name: examplesvcname
    namespace: demo
