apiVersion: v1
kind: Namespace
metadata:
  name: openshift-aws-vpce-operator
---
apiVersion: avo.openshift.io/v1alpha1
kind: VpcEndpoint
metadata:
  name: demo
  namespace: openshift-aws-vpce-operator
spec:
  subdomainName: "splunk"
  serviceName: "com.amazonaws.vpce.us-east-2.vpce-svc-00935f365dbc6ad80"
  securityGroup:
    ingressRules:
      - fromPort: 9997
        toPort: 9997
        protocol: tcp
