---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-aws-vpce-operator
---
apiVersion: avo.openshift.io/v1alpha2
kind: VpcEndpoint
metadata:
  name: demo
  namespace: openshift-aws-vpce-operator
spec:
  serviceName: "com.amazonaws.vpce.us-east-2.vpce-svc-0dd975383622be88c"
  securityGroup:
    ingressRules:
      - fromPort: 6443
        toPort: 6443
        protocol: tcp
  vpc:
    subnetIds:
      - "subnet-0e4d3ac883d228789"
