# permissions for end users to edit vpcendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpcendpoint-editor-role
rules:
- apiGroups:
  - avo.openshift.io
  resources:
  - vpcendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - avo.openshift.io
  resources:
  - vpcendpoints/status
  verbs:
  - get
