apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-vpce-operator
rules:
  - apiGroups:
    - config.openshift.io
    resources:
    - infrastructures
    - dnses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - avo.openshift.io
    resources:
    - vpcendpoints
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    - services/finalizers
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
