apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-vpce-operator
  namespace: openshift-aws-vpce-operator
rules:
  - apiGroups:
    - avo.openshift.io
    resources:
    - vpcendpoints
    verbs:
    - create
    - delete
    - update
    - patch
  - apiGroups:
    - avo.openshift.io
    resources:
    - vpcendpoints/status
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - avo.openshift.io
    resources:
    - vpcendpoints/finalizers
    verbs:
    - update
