apiVersion: v1
kind: Service
metadata:
  name: aws-vpce-operator-metrics
  namespace: openshift-aws-vpce-operator
spec:
  selector:
    name: aws-vpce-operator
  ports:
    - name: http-metrics
      port: 80
      protocol: TCP
      targetPort: 8080
